services:
  bin-it:
    build:
      target: development
    container_name: bin-it
    ports:
      - '8080:8080'
    volumes:
      - ./:/bin-it
    networks:
      - bin-it

  mongodb:
    image: mongo:latest
    container_name: bin-it-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    networks:
      - bin-it

  mongo-express:
    image: mongo-express:latest
    container_name: bin-it-mongo-express
    ports:
      - '8081:8081'
    networks:
      - bin-it

volumes:
  mongodb-data:

networks:
  bin-it:
    driver: bridge
    name: bin-it
